### ISSUE TITLE
tokens.txt

### ISSUE THREAD

**Issue by zferic** [google/gematria#45]
Hi,

I'm trying to follow the g3doc inference-api.md documentation, but when I run the command I'm missing the /tmp/tokens.txt file. Could you please let me know how to generate this file?

Thanks,
Z

**Comment by zferic** [comment]
Figured it out!

**Comment by HuXiabing** [comment]
how do you figured it out? many thanks

**Comment by boomanaiden154** [comment]
> how do you figured it out? many thanks

Not entirely sure how the original poster solved the issue. As of July though, we have the `//gematria/datasets/python:extract_tokens_file` binary which will take in a TFRecord and output the tokens contained within the TFRecord.

I need to find some time to update the documentation on dataset collection to better point this and the other tools out.
